version: "3"

networks:
  central:
    name: traefik_central
    external: true    

services:
  aquarelle_website:
    image: ghcr.io/casimodo/police_rp:latest
    networks:
      - central
    environment:
      NODE_ENV: prod
    deploy:
      update_config:
        order: start-first
      labels:
        - traefik.enable=true
        - traefik.http.routers.police_rp.rule=Host(`reality-police.gaminghug.ovh`)
        - traefik.http.routers.police_rp.entrypoints=websecure
        - traefik.http.services.police_rp.loadbalancer.server.port=8088
        - traefik.http.routers.police_rp.service=police_rp
        - traefik.http.routers.police_rp.tls.certresolver=lets-encrypt
